/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package model;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class EmployeeDatabase extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1534495197640047593L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EmployeeDatabase\",\"namespace\":\"model\",\"fields\":[{\"name\":\"name\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"salary\",\"type\":[\"null\",\"double\"],\"default\":null},{\"name\":\"age\",\"type\":\"int\"},{\"name\":\"empMobile\",\"type\":[\"null\",\"long\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.Double salary;
  @Deprecated public int age;
  @Deprecated public java.lang.Long empMobile;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EmployeeDatabase() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param salary The new value for salary
   * @param age The new value for age
   * @param empMobile The new value for empMobile
   */
  public EmployeeDatabase(java.lang.CharSequence name, java.lang.Double salary, java.lang.Integer age, java.lang.Long empMobile) {
    this.name = name;
    this.salary = salary;
    this.age = age;
    this.empMobile = empMobile;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return salary;
    case 2: return age;
    case 3: return empMobile;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: salary = (java.lang.Double)value$; break;
    case 2: age = (java.lang.Integer)value$; break;
    case 3: empMobile = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'salary' field.
   * @return The value of the 'salary' field.
   */
  public java.lang.Double getSalary() {
    return salary;
  }

  /**
   * Sets the value of the 'salary' field.
   * @param value the value to set.
   */
  public void setSalary(java.lang.Double value) {
    this.salary = value;
  }

  /**
   * Gets the value of the 'age' field.
   * @return The value of the 'age' field.
   */
  public java.lang.Integer getAge() {
    return age;
  }

  /**
   * Sets the value of the 'age' field.
   * @param value the value to set.
   */
  public void setAge(java.lang.Integer value) {
    this.age = value;
  }

  /**
   * Gets the value of the 'empMobile' field.
   * @return The value of the 'empMobile' field.
   */
  public java.lang.Long getEmpMobile() {
    return empMobile;
  }

  /**
   * Sets the value of the 'empMobile' field.
   * @param value the value to set.
   */
  public void setEmpMobile(java.lang.Long value) {
    this.empMobile = value;
  }

  /**
   * Creates a new EmployeeDatabase RecordBuilder.
   * @return A new EmployeeDatabase RecordBuilder
   */
  public static model.EmployeeDatabase.Builder newBuilder() {
    return new model.EmployeeDatabase.Builder();
  }

  /**
   * Creates a new EmployeeDatabase RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EmployeeDatabase RecordBuilder
   */
  public static model.EmployeeDatabase.Builder newBuilder(model.EmployeeDatabase.Builder other) {
    return new model.EmployeeDatabase.Builder(other);
  }

  /**
   * Creates a new EmployeeDatabase RecordBuilder by copying an existing EmployeeDatabase instance.
   * @param other The existing instance to copy.
   * @return A new EmployeeDatabase RecordBuilder
   */
  public static model.EmployeeDatabase.Builder newBuilder(model.EmployeeDatabase other) {
    return new model.EmployeeDatabase.Builder(other);
  }

  /**
   * RecordBuilder for EmployeeDatabase instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EmployeeDatabase>
    implements org.apache.avro.data.RecordBuilder<EmployeeDatabase> {

    private java.lang.CharSequence name;
    private java.lang.Double salary;
    private int age;
    private java.lang.Long empMobile;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(model.EmployeeDatabase.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.salary)) {
        this.salary = data().deepCopy(fields()[1].schema(), other.salary);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.age)) {
        this.age = data().deepCopy(fields()[2].schema(), other.age);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.empMobile)) {
        this.empMobile = data().deepCopy(fields()[3].schema(), other.empMobile);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing EmployeeDatabase instance
     * @param other The existing instance to copy.
     */
    private Builder(model.EmployeeDatabase other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.salary)) {
        this.salary = data().deepCopy(fields()[1].schema(), other.salary);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.age)) {
        this.age = data().deepCopy(fields()[2].schema(), other.age);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.empMobile)) {
        this.empMobile = data().deepCopy(fields()[3].schema(), other.empMobile);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public model.EmployeeDatabase.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public model.EmployeeDatabase.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'salary' field.
      * @return The value.
      */
    public java.lang.Double getSalary() {
      return salary;
    }

    /**
      * Sets the value of the 'salary' field.
      * @param value The value of 'salary'.
      * @return This builder.
      */
    public model.EmployeeDatabase.Builder setSalary(java.lang.Double value) {
      validate(fields()[1], value);
      this.salary = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'salary' field has been set.
      * @return True if the 'salary' field has been set, false otherwise.
      */
    public boolean hasSalary() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'salary' field.
      * @return This builder.
      */
    public model.EmployeeDatabase.Builder clearSalary() {
      salary = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'age' field.
      * @return The value.
      */
    public java.lang.Integer getAge() {
      return age;
    }

    /**
      * Sets the value of the 'age' field.
      * @param value The value of 'age'.
      * @return This builder.
      */
    public model.EmployeeDatabase.Builder setAge(int value) {
      validate(fields()[2], value);
      this.age = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'age' field has been set.
      * @return True if the 'age' field has been set, false otherwise.
      */
    public boolean hasAge() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'age' field.
      * @return This builder.
      */
    public model.EmployeeDatabase.Builder clearAge() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'empMobile' field.
      * @return The value.
      */
    public java.lang.Long getEmpMobile() {
      return empMobile;
    }

    /**
      * Sets the value of the 'empMobile' field.
      * @param value The value of 'empMobile'.
      * @return This builder.
      */
    public model.EmployeeDatabase.Builder setEmpMobile(java.lang.Long value) {
      validate(fields()[3], value);
      this.empMobile = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'empMobile' field has been set.
      * @return True if the 'empMobile' field has been set, false otherwise.
      */
    public boolean hasEmpMobile() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'empMobile' field.
      * @return This builder.
      */
    public model.EmployeeDatabase.Builder clearEmpMobile() {
      empMobile = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public EmployeeDatabase build() {
      try {
        EmployeeDatabase record = new EmployeeDatabase();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.salary = fieldSetFlags()[1] ? this.salary : (java.lang.Double) defaultValue(fields()[1]);
        record.age = fieldSetFlags()[2] ? this.age : (java.lang.Integer) defaultValue(fields()[2]);
        record.empMobile = fieldSetFlags()[3] ? this.empMobile : (java.lang.Long) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
